### ISSUE TITLE
PredcircRNA.py:904: RuntimeWarning: [WARN] ?

### ISSUE THREAD

**Issue by zhenyisong** [xypan1232/PredcircRNA#1]
I installed this prediction pipeline in my centos 7(centos-release-7-2.1511.el7.centos.2.10.x86_64).  When I used the suggested test set to assess the script, I found one piece of the thrown-out warning message: 

"
In file /home/zhenyisong/software/shogun/src/shogun/io/SerializableFile.cpp line 122: Could not read `kernel/kernel_array/array/m_distance' from `models/mkl.dat'!
  status = new_mkl.load_serializable(fstream) 
"
 It seemed that there missed some paramter which should be defined in mkl.dat and the program might use the default setting somewhere to call other function in shogun.

Here I want to make sure whether the warning message will lead to error predition or non-optimized performance.

Thanks.

-------test_bed_out------
chr2 69304539 69318051 + gene1  circularRNA
chr7 138593736 138597206 - gene2        circularRNA
chr22 39134591 39137055 - gene3         circularRNA

**Comment by xypan1232** [comment]
This warning should not affect the prediction.

Is shogun version v3.2.0? which is used in my ubuntu system.

**Comment by zhenyisong** [comment]
I git cloned the shogut and It is 5.0.0. Thanks. Now I can proceed to next step.
